name: 🧪 Release

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: macos-13
    strategy:
      matrix:
        xcode_version: ["11.7", "12.5", "13.3"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Xcode ${{ matrix.xcode_version }}
        uses: actions/setup-swift@v2
        with:
          xcode-version: ${{ matrix.xcode_version }}
      - name: Version
        run: swift --version
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --enable-code-coverage
      - name: Gather code coverage
        run: xcrun llvm-cov export -format="lcov" .build/debug/AudioWaveLibPackageTests.xctest/Contents/MacOS/AudioWaveLibPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage_report.lcov
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Run SwiftLint
        run: swiftlint
      - name: Validate Documentation
        run: swift build --docs
