name: 🧪 Build

on: [push, pull_request]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos-build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --enable-code-coverage
      - name: Gather code coverage
        run: xcrun llvm-cov export -format="lcov" .build/debug/AudioWaveLibPackageTests.xctest/Contents/MacOS/AudioWaveLibPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov
      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage_report.lcov
          fail_ci_if_error: false
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Run SwiftLint
        run: swiftlint --strict
      - name: Install SwiftFormat
        run: brew install swiftformat
      - name: Run SwiftFormat
        run: swiftformat --lint .
