name: 🧪 Build

on: [push, pull_request]

jobs:
  xcode_15_1:
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.1.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Version
        run: swift --version
      - name: Build
        run: swift test --enable-code-coverage --filter do_not_test
      - name: Test
        run: swift test --enable-code-coverage --skip-build
      - name: Gather code coverage
        run: xcrun llvm-cov export -format="lcov" .build/debug/SwiftDrawPackageTests.xctest/Contents/MacOS/SwiftDrawPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage_report.lcov

  xcode_14_3:
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --skip-build

  linux_5_7:
    runs-on: ubuntu-latest
    container: swift:5.7
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --skip-build

  linux_5_9:
    runs-on: ubuntu-latest
    container: swift:5.9
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --skip-build